name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
        env:
          OPEN_WEATHER_MAP_KEY: ${{secrets.OPEN_WEATHER_MAP_KEY}}
      - name: Get current time
        id: current-time
        run: echo "CURRENT_TIME=$(TZ='Asia/Ho_Chi_Minh' date)" >> $GITHUB_ENV
      - name: Commit and push new README.md
        run: |-
          git diff
          git config --global user.email "${{secrets.GLOBAL_USER_EMAIL}}"
          git config --global user.name "${{secrets.GLOBAL_USER_NAME}}"
          git commit -a -m "Automated publish: ${{ env.CURRENT_TIME }}" || exit 0
          git push